#ifndef METADATA_HPP
#define METADATA_HPP

#include "wx/wx.h"

// This dialog can be used to create a new file or to edit the current file
// metadata

class MetadataDialog : public wxDialog {
public:
  MetadataDialog(wxWindow* parent, bool newFile);
  ~MetadataDialog();
  std::string name;
  std::string author;
  unsigned short gridSize = 5;
  // DATE and VERSION are generated by CORE
};

#endif
